// Dependency-free checks against the expressions generated by the actual JSX.
// This small AE host stub cannot verify Adobe's GUI or import/render implementation.
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '..', 'Radial Carousel.jsx'), 'utf8');
new vm.Script(source);
new vm.Script(fs.readFileSync(path.join(__dirname, 'Smoke Test.jsx'), 'utf8'));
new vm.Script(fs.readFileSync(path.join(__dirname, 'Arc Test.jsx'), 'utf8'));
new vm.Script(fs.readFileSync(path.join(__dirname, 'Bend Test.jsx'), 'utf8'));
new vm.Script(fs.readFileSync(path.join(__dirname, 'Unfolded Orbit Test.jsx'), 'utf8'));
let checks = 0;
const near = (a, b) => { assert.ok(Math.abs(a - b) < 1e-7, `${a} != ${b}`); checks++; };
const liveItems = [];
let nextItemID = 1;
let importCount = 0;
function track(item) {
    liveItems.push(item);
    item.remove = () => { const i = liveItems.indexOf(item); if (i >= 0) liveItems.splice(i, 1); };
    return item;
}
class Property {
    constructor() { this.value = 0; this.expression = ''; this.numKeys = 0; }
    setValue(v) { this.value = v; }
    setValueAtTime(t, v) { this.lastKey = [t, v]; }
}
class Group {
    constructor(type) { this.props = {}; this.effects = []; this.indexed = type === 'ADBE Effect Parade' || type === 'ADBE Mask Parade'; }
    property(name) { return this.effects.find(e => e.name === name) || (this.indexed ? null : (this.props[name] ||= new Property())); }
    addProperty() { const e = new Group(); this.effects.push(e); return e; }
}
class FootageItem {
    constructor(file) { Object.assign(this, {id: nextItemID++, file, name: file.name, width: file.width, height: file.height, pixelAspect: file.pixelAspect || 1, mainSource: {isStill: true}}); }
}
class ImportOptions { constructor(file) { this.file = file; } canImportAs() { return true; } }
class Layer {
    constructor(comp, footage) { this.containingComp = comp; this.source = footage; this.groups = {}; this.inPoint = 0; }
    property(name) { return this.groups[name] ||= name === 'ADBE Time Remapping' ? new Property() : new Group(name); }
    get index() { return this.containingComp.list.indexOf(this) + 1; }
    remove() { this.containingComp.list.splice(this.containingComp.list.indexOf(this), 1); }
    moveToBeginning() { this.remove(); this.containingComp.list.unshift(this); }
}
class CompItem {
    constructor(name, width, height, pixelAspect, duration, fps) {
        Object.assign(this, {id: nextItemID++, name, width, height, pixelAspect, duration, fps, frameDuration: 1 / fps, list: [], time: 0});
        this.layers = {
            add: f => { const l = new Layer(this, f); this.list.unshift(l); return l; },
            addNull: () => this.layers.add(track(new FootageItem({name: 'Null', width: 100, height: 100})))
        };
    }
    get numLayers() { return this.list.length; }
    get selectedLayers() { return this.list.filter(l => l.selected); }
    layer(i) { return this.list[i - 1]; }
    openInViewer() { app.project.activeItem = this; }
}
const app = {
    beginUndoGroup() { this.undoDepth++; }, endUndoGroup() { this.undoDepth--; }, undoDepth: 0,
    project: {
        get numItems() { return liveItems.length; },
        item(i) { return liveItems[i - 1]; },
        importFile(options) {
            importCount++;
            assert.equal(options.sequence, false);
            if (options.file.bad) throw Error('Invalid image');
            return track(new FootageItem(options.file));
        },
        items: {
            addFolder() {
                const folder = track({});
                const remove = folder.remove;
                folder.remove = () => { for (const i of liveItems.slice()) if (i.parentFolder === folder) i.remove(); remove(); };
                return folder;
            },
            addComp: (...args) => track(new CompItem(...args))
        }
    }
};
const context = {app, CompItem, FootageItem, ImportOptions, ImportAsType: {FOOTAGE: 1}, MaskMode: {INTERSECT: 4}, isValid: item => !!item && !item.invalid};
// Cut only the GUI construction from a test copy, exposing the unmodified rig builder.
vm.runInNewContext(source.slice(0, source.indexOf('    var win =')) + 'this.api = {build: build, number: number, configure: configure, control: control, orbitState: orbitState, orbitDuration: orbitDuration};})(this);', context);
const {api} = context;
const files = [{name: 'Portrait', width: 100, height: 160}, {name: 'Landscape', width: 200, height: 100}, {name: 'Anamorphic', width: 100, height: 100, pixelAspect: 2}].map(f => ({...f, exists: true}));
const s = {radius: 240, size: 160, speed: 30, angle: -90, offset: 0, upright: true, rounded: false, cornerRadius: 24, shuffle: false, seed: 1, width: 800, height: 800, duration: 12, fps: 30};
const ctrl = api.build(s, files, null);
const comp = ctrl.containingComp;
assert.equal(comp.numLayers, 4);
const layers = comp.list.filter(l => l.parent === ctrl);
function evaluate(layer, property, time, rotation = 0) {
    const parent = {effect: n => () => api.control(ctrl, n).value, transform: {rotation}};
    return vm.runInNewContext(layer.property('ADBE Transform Group').property(property).expression, {
        parent, effect: parent.effect, time, inPoint: 0, value: 0,
        thisLayer: {source: layer.source}, thisComp: comp
    });
}
for (const upright of [true, false]) {
    for (const speed of [30, -30, 0]) {
        for (const offset of [0, 90, 180]) {
            api.configure(ctrl, {...s, upright, speed, offset});
            for (const time of [0, 1.5, 3, 7.5, 12]) {
                const rotation = evaluate(ctrl, 'ADBE Rotate Z', time);
                near(rotation, time * speed);
                for (const l of layers) {
                    const p = evaluate(l, 'ADBE Position', time, rotation);
                    near(Math.hypot(...p), 240);
                    const slot = files.findIndex(f => f.name === l.source.name);
                    const angle = -90 + slot * 120;
                    near(p[0], 240 * Math.cos(angle * Math.PI / 180));
                    near(p[1], 240 * Math.sin(angle * Math.PI / 180));
                    const local = evaluate(l, 'ADBE Rotate Z', time, rotation);
                    near(local + rotation, upright ? offset : angle + rotation + 90 + offset);
                    const scale = evaluate(l, 'ADBE Scale', time, rotation);
                    near(scale[0], scale[1]);
                    near(Math.max(l.source.width * l.source.pixelAspect, l.source.height) * scale[0] / 100, 160);
                }
            }
        }
    }
}
api.configure(ctrl, {...s, radius: 0});
for (const l of layers) near(Math.hypot(...evaluate(l, 'ADBE Position', 0)), 0);
const beforeItems = liveItems.length, beforeLayers = comp.numLayers;
assert.throws(() => api.build(s, [], comp));
assert.throws(() => api.build(s, [{exists: false, fsName: 'missing.png'}], comp));
assert.throws(() => api.build(s, [files[0], {exists: true, bad: true}], comp));
assert.equal(liveItems.length, beforeItems);
assert.equal(comp.numLayers, beforeLayers);
assert.equal(app.undoDepth, 0);
for (const input of ['', ' ', '100px', 'NaN', 'Infinity', '-1', '101']) assert.throws(() => api.number(input, 'Size', 1, 100, false));
assert.throws(() => api.number('4.5', 'Width', 4, 30000, true));
near(api.number('29.97', 'Frame rate', 1, 99, false), 29.97);
const radius = api.control(ctrl, 'Radius');
radius.numKeys = 2;
comp.time = 3;
api.configure(ctrl, {...s, radius: 300});
assert.deepEqual(Array.from(radius.lastKey), [3, 300]);

// Existing project footage must retain identity, interpretation, and its original folder.
const originalFolder = app.project.items.addFolder();
const existing = track(new FootageItem({name: 'Imported image', width: 100, height: 160}));
existing.parentFolder = originalFolder;
const interpretation = existing.mainSource;
const oldImports = importCount;
const reuse = api.build(s, [{item: existing, name: existing.name}], comp);
assert.equal(importCount, oldImports);
assert.equal(comp.list.find(l => l.parent === reuse).source, existing);
assert.equal(existing.parentFolder, originalFolder);
assert.equal(existing.mainSource, interpretation);
const mixed = api.build(s, [{item: existing, name: existing.name}, files[0]], comp);
assert.equal(importCount, oldImports + 1);
assert.equal(comp.list.filter(l => l.parent === mixed).length, 2);
assert.equal(existing.parentFolder, originalFolder);
const beforeFailureItems = liveItems.length, beforeFailureLayers = comp.numLayers;
assert.throws(() => api.build(s, [{item: existing, name: existing.name}, {...files[0], bad: true}], comp));
assert.equal(liveItems.length, beforeFailureItems);
assert.equal(comp.numLayers, beforeFailureLayers);
const realAdd = comp.layers.add;
comp.layers.add = f => { if (f === existing) throw Error('Layer creation failed'); return realAdd(f); };
assert.throws(() => api.build(s, [{item: existing, name: existing.name}], comp));
comp.layers.add = realAdd;
assert.equal(liveItems.length, beforeFailureItems);
assert.equal(comp.numLayers, beforeFailureLayers);
assert.ok(liveItems.includes(existing));
assert.equal(existing.parentFolder, originalFolder);
for (const problem of ['invalid', 'footageMissing']) {
    existing[problem] = true;
    assert.throws(() => api.build(s, [{item: existing, name: existing.name}], comp), /unavailable/);
    existing[problem] = false;
}

// Execute the real panel callbacks with a minimal ScriptUI host, not copies of their logic.
class UI {
    constructor(type, text = '') { Object.assign(this, {type, text, children: [], items: [], preferredSize: {}, size: [400, 850], layout: {layout() {}, resize() {}}}); }
    add(type, bounds, text) {
        const child = new UI(type, type === 'item' ? bounds : text);
        child.parent = this;
        this.children.push(child);
        if (type === 'item') { child.index = this.items.length; this.items.push(child); }
        return child;
    }
    removeAll() { this.items = []; }
    center() {}
    show() { this.visible = true; }
}
let window;
class Window extends UI { constructor(type, title) { super(type, title); window = this; } }
class File { static fs = 'Windows'; static decode(s) { return decodeURI(s); } }
const alerts = [];
const uiContext = vm.createContext({...context, Window, Panel: class {}, File, alert: e => alerts.push(e)});
app.project.activeItem = comp;
vm.runInContext(source, uiContext);
const find = (type, text, node = window) => node.type === type && (text === undefined || node.text === text) ? node : node.children.map(c => find(type, text, c)).find(Boolean);
const projectButton = find('button', 'Use Project Selection');
const imageList = find('listbox');
const createButton = find('button', 'Create Radial Carousel');
const carouselMenu = find('dropdownlist');
carouselMenu.selection = carouselMenu.items[0];
carouselMenu.onChange();
app.project.selection = [];
projectButton.onClick();
assert.match(alerts.pop(), /Project panel/);
const movie = new FootageItem({name: 'Movie', width: 100, height: 100}); movie.mainSource.isStill = false;
const solid = new FootageItem({name: 'Solid', width: 100, height: 100}); solid.file = null;
const offline = new FootageItem({name: 'Offline', width: 100, height: 100}); offline.footageMissing = true;
const sameFileDifferentItem = new FootageItem(existing.file);
app.project.selection = [existing, movie, originalFolder, solid, offline, sameFileDifferentItem];
projectButton.onClick();
assert.equal(imageList.items.length, 2);
assert.match(imageList.items[0].text, /\[Project\] Imported image/);
projectButton.onClick();
assert.equal(imageList.items.length, 2, 'Repeated selection is deduplicated by item ID');
assert.equal(createButton.enabled, true);
const uiImports = importCount, uiLayers = comp.numLayers;
app.project.activeItem = existing; // Project browser focus must not lose the remembered destination.
createButton.onClick();
assert.equal(alerts.length, 0);
assert.equal(comp.numLayers, uiLayers + 3);
assert.equal(importCount, uiImports);
assert.equal(existing.parentFolder, originalFolder);
const roundedToggle = find('checkbox', 'Rounded corners');
const cornerInput = find('statictext', 'Corner radius (px)');
const cornerRow = cornerInput.parent;
const cornerField = cornerRow.children.find(c => c.type === 'edittext');
roundedToggle.value = true;
roundedToggle.onClick();
assert.equal(cornerField.enabled, true);
cornerField.text = '32';
const uiController = comp.list[0];
find('button', 'Update Carousel').onClick();
assert.equal(alerts.length, 0);
near(api.control(uiController, 'Rounded Corners').value, 1);
near(api.control(uiController, 'Corner Radius').value, 32);
roundedToggle.value = false;
find('button', 'Load Selected').onClick();
assert.equal(roundedToggle.value, true);
assert.equal(cornerField.text, '32');
find('button', 'New Seed').onClick();
assert.equal(find('checkbox', 'Shuffle image order').value, true);
find('button', 'Update Carousel').onClick();
assert.equal(alerts.length, 0);
const newSeed = api.control(uiController, 'Arrangement Seed').value;
assert.ok(Number.isInteger(newSeed) && newSeed >= 0 && newSeed <= 999999 && newSeed !== 1);
near(api.control(uiController, 'Shuffle Images').value, 1);
find('checkbox', 'Shuffle image order').value = false;
find('button', 'Load Selected').onClick();
assert.equal(find('checkbox', 'Shuffle image order').value, true);
uiContext.fixtureFile = {name: 'disk.png', fsName: 'F:/disk.png', exists: true};
vm.runInContext('File.openDialog = function () { return [fixtureFile]; };', uiContext);
assert.equal(find('button', 'Add Files...').enabled, false, 'Existing image list is read-only');
assert.equal(find('button', 'Use Project Selection').enabled, false);
assert.equal(createButton.enabled, false, 'Loading an existing carousel prevents accidental rebuilding');
carouselMenu.selection = carouselMenu.items[0];
carouselMenu.onChange();
projectButton.onClick();
find('button', 'Add Files...').onClick();
find('button', 'Add Files...').onClick();
assert.equal(imageList.items.length, 3, 'Disk entries work alongside project entries and deduplicate');
imageList.selection = imageList.items[0];
find('button', 'Remove').onClick();
assert.equal(imageList.items.length, 2);
find('button', 'Clear').onClick();
assert.equal(imageList.items.length, 0);
assert.equal(createButton.enabled, false);

// Test mask geometry emitted by the script for both orientations and varied image sizes/PAR.
for (const upright of [true, false]) {
    for (const rounded of [true, false]) {
        for (const cornerRadius of [0, 24, 10000]) {
            api.configure(ctrl, {...s, upright, rounded, cornerRadius});
            for (const l of layers) {
                const masks = l.property('ADBE Mask Parade');
                assert.equal(masks.effects.length, 1, 'Apply reuses the existing mask');
                const mask = masks.property('RC Rounded Corners');
                assert.equal(mask.maskMode, context.MaskMode.INTERSECT);
                const shape = vm.runInNewContext(mask.property('ADBE Mask Shape').expression, {
                    parent: {effect: n => () => api.control(ctrl, n).value},
                    thisLayer: {source: l.source}, thisComp: comp,
                    createPath: (points, ins, outs, closed) => ({points, ins, outs, closed})
                });
                assert.equal(shape.closed, true);
                const w = l.source.width, h = l.source.height, pa = l.source.pixelAspect / comp.pixelAspect;
                const scale = s.size / Math.max(w * pa, h);
                const r = rounded ? Math.min(cornerRadius, w * pa * scale / 2, h * scale / 2) : 0;
                assert.equal(shape.points.length, r > 0 ? 8 : 4);
                for (const p of shape.points) {
                    assert.ok(p[0] >= 0 && p[0] <= w && p[1] >= 0 && p[1] <= h);
                }
                if (r > 0) {
                    near(shape.points[0][0] * scale * pa, r);
                    near(shape.points[2][1] * scale, r);
                    assert.equal(shape.ins.length, 8);
                    assert.equal(shape.outs.length, 8);
                    // Midpoint of the top-right cubic lies on the intended circular arc.
                    const a = shape.points[1], b = shape.points[2];
                    const mid = a.map((v, axis) => (v + 3 * (v + shape.outs[1][axis]) + 3 * (b[axis] + shape.ins[2][axis]) + b[axis]) / 8);
                    near(Math.hypot((mid[0] - a[0]) * scale * pa, (mid[1] - b[1]) * scale), r);
                } else {
                    assert.deepEqual(Array.from(shape.points[0]), [0, 0]);
                    assert.deepEqual(Array.from(shape.points[2]), [w, h]);
                }
            }
        }
    }
}
// Old rigs acquire the optional controls/mask, while a user's existing mask remains intact.
const oldEffects = ctrl.property('ADBE Effect Parade');
oldEffects.effects = oldEffects.effects.filter(e => !['Rounded Corners', 'Corner Radius'].includes(e.name));
const oldMasks = layers[0].property('ADBE Mask Parade');
oldMasks.effects = [];
const userMask = oldMasks.addProperty(); userMask.name = 'User artwork mask';
api.configure(ctrl, {...s, rounded: true, cornerRadius: 40});
assert.ok(oldMasks.effects.includes(userMask));
assert.equal(oldMasks.effects.length, 2);
near(api.control(ctrl, 'Corner Radius').value, 40);
api.configure(ctrl, {...s, rounded: false});
assert.equal(oldMasks.effects.length, 2);

// Every layer must use the same permutation, with reproducible seeds and distinct slots.
api.control(ctrl, 'Radius').numKeys = 0;
function arrangement(seed, shuffle = true, upright = false) {
    api.configure(ctrl, {...s, seed, shuffle, upright, rounded: true});
    return layers.map(l => {
        const rotation = evaluate(ctrl, 'ADBE Rotate Z', 3);
        const p = evaluate(l, 'ADBE Position', 3, rotation);
        near(Math.hypot(...p), s.radius);
        const imageRotation = evaluate(l, 'ADBE Rotate Z', 3, rotation);
        if (upright) near(imageRotation + rotation, 0);
        else {
            // Image top follows its shuffled radial position, before the shared parent rotation.
            const a = (imageRotation - 90) * Math.PI / 180;
            near(Math.cos(a), p[0] / s.radius);
            near(Math.sin(a), p[1] / s.radius);
        }
        return Array.from(p);
    });
}
const variations = new Set();
for (const seed of [0, 1, 2, 3, 42, 999999]) {
    const points = arrangement(seed);
    assert.equal(new Set(points.map(p => p.map(n => n.toFixed(7)).join(','))).size, layers.length);
    const expected = JSON.stringify(points);
    variations.add(expected);
    arrangement(123456);
    assert.equal(JSON.stringify(arrangement(seed)), expected, 'Reusing seed restores the exact permutation');
    arrangement(seed, true, true);
}
assert.ok(variations.size > 1, 'Different seeds produce variations');
assert.deepEqual(arrangement(0, false), arrangement(999999, false), 'Disable shuffle restores original order');
assert.throws(() => api.number('1.5', 'Arrangement seed', 0, 999999, true));
assert.throws(() => api.number('-1', 'Arrangement seed', 0, 999999, true));

// Upgrade the precise v1.0-v1.2 expression format and preserve original image order.
const expectedUpgrade = arrangement(42);
oldEffects.effects = oldEffects.effects.filter(e => !['Shuffle Images', 'Arrangement Seed'].includes(e.name));
for (const l of layers) {
    const slot = files.findIndex(f => f.name === l.source.name);
    const header = 'var a = parent.effect("Start Angle")(1) + ' + (slot * 120) + ';\n';
    l.property('ADBE Transform Group').property('ADBE Position').expression = header + 'var r = parent.effect("Radius")(1); var rad = a * Math.PI / 180; [r * Math.cos(rad), r * Math.sin(rad)];';
    l.property('ADBE Transform Group').property('ADBE Rotate Z').expression = header + 'parent.effect("Keep Upright")(1) > 0.5 ? -parent.transform.rotation : a + 90;';
}
assert.deepEqual(arrangement(42), expectedUpgrade);
const solo = api.build({...s, shuffle: true, seed: 0}, [files[0]], null);
const soloLayer = solo.containingComp.list.find(l => l.parent === solo);
const soloPosition = vm.runInNewContext(soloLayer.property('ADBE Transform Group').property('ADBE Position').expression, {
    parent: {effect: n => () => api.control(solo, n).value}
});
near(soloPosition[0], 0); near(soloPosition[1], -s.radius);

// Reopen the panel with only project data remaining: detect, recover, and update in place.
const uiChildren = comp.list.filter(l => l.parent === uiController);
uiChildren.sort((a, b) => Number(a.property('ADBE Transform Group').property('ADBE Position').expression.match(/var slot = (\d+)/)[1]) - Number(b.property('ADBE Transform Group').property('ADBE Position').expression.match(/var slot = (\d+)/)[1]));
uiChildren[0].source.name = 'First recovered image';
uiChildren[1].source.name = 'Second recovered image';
uiController.name = 'Renamed existing carousel';
comp.name = 'Existing composition';
api.configure(uiController, {...s, radius: 410.5, size: 130, speed: -18, angle: 75, offset: 12, rounded: true, cornerRadius: 44, shuffle: true, seed: 384});
for (const l of comp.list) l.selected = false;
uiChildren[0].selected = true;
uiChildren[0].moveToBeginning();
app.project.activeItem = comp;
const reopenItems = liveItems.length, reopenLayers = comp.numLayers, reopenImports = importCount;
const effectCounts = comp.list.map(l => l.property('ADBE Effect Parade').effects.length);
vm.runInContext(source, uiContext);
const inputFor = label => find('statictext', label).parent.children.find(c => c.type === 'edittext');
const reopenedMenu = find('dropdownlist');
assert.equal(reopenedMenu.selection.controller, uiController, 'Selected child auto-detects its existing controller');
assert.match(reopenedMenu.selection.text, /Existing composition.*Renamed existing carousel/);
assert.equal(inputFor('Radius (px)').text, '410.5');
assert.equal(inputFor('Image longest edge (px)').text, '130');
assert.equal(inputFor('Speed (degrees/sec)').text, '18');
assert.equal(find('checkbox', 'Clockwise rotation').value, false);
assert.equal(inputFor('Corner radius (px)').text, '44');
assert.equal(inputFor('Arrangement seed').text, '384');
assert.equal(find('checkbox', 'Rounded corners').value, true);
assert.equal(find('checkbox', 'Shuffle image order').value, true);
assert.equal(find('listbox').items.length, 2);
assert.match(find('listbox').items[0].text, /First recovered image/);
assert.match(find('listbox').items[1].text, /Second recovered image/);
assert.equal(find('button', 'Update Carousel').enabled, true);
assert.equal(find('button', 'Create Radial Carousel').enabled, false);
assert.equal(liveItems.length, reopenItems, 'Opening the GUI creates no project assets');
assert.equal(comp.numLayers, reopenLayers);
assert.equal(importCount, reopenImports);
assert.deepEqual(comp.list.map(l => l.property('ADBE Effect Parade').effects.length), effectCounts, 'Opening the GUI does not add effects');
for (const l of comp.list) l.selected = false;
app.project.activeItem = solo.containingComp;
inputFor('Radius (px)').text = '512';
find('button', 'Update Carousel').onClick();
assert.equal(alerts.length, 0);
near(api.control(uiController, 'Radius').value, 512);
near(api.control(solo, 'Radius').value, s.radius);
assert.equal(comp.numLayers, reopenLayers);
assert.equal(importCount, reopenImports, 'Updating a recovered rig does not reimport its images');

reopenedMenu.selection = reopenedMenu.items.find(i => i.controller === ctrl);
reopenedMenu.onChange();
assert.equal(find('listbox').items.length, 3, 'Dropdown switches to a different existing carousel');
inputFor('Radius (px)').text = '123';
find('button', 'Update Carousel').onClick();
near(api.control(ctrl, 'Radius').value, 123);
near(api.control(uiController, 'Radius').value, 512);
ctrl.name = 'Renamed after opening the panel';
find('button', 'Refresh').onClick();
assert.equal(reopenedMenu.selection.controller, ctrl, 'Refresh preserves the chosen target');
assert.match(reopenedMenu.selection.text, /Renamed after opening/);
const savedEffects = ctrl.property('ADBE Effect Parade').effects;
ctrl.property('ADBE Effect Parade').effects = savedEffects.filter(e => e.name !== 'Radius');
reopenedMenu.onChange();
assert.match(alerts.pop(), /missing its 'Radius' control/, 'Broken controller identifies the missing control instead of dereferencing null');
assert.equal(find('button', 'Update Carousel').enabled, false, 'Failed loading cannot update a previous target');
ctrl.property('ADBE Effect Parade').effects = savedEffects;
reopenedMenu.onChange();
ctrl.remove(); ctrl.invalid = true;
find('button', 'Update Carousel').onClick();
assert.match(alerts.pop(), /Refresh/);
find('button', 'Refresh').onClick();
assert.equal(reopenedMenu.selection.controller, undefined);
assert.equal(find('button', 'Update Carousel').enabled, false);
assert.equal(find('listbox').items.length, 0);

// Multiple carousels with no active composition require an explicit choice.
app.project.activeItem = null;
vm.runInContext(source, uiContext);
assert.equal(find('dropdownlist').selection.controller, undefined);
assert.ok(find('dropdownlist').items.length > 2);
assert.equal(find('button', 'Update Carousel').enabled, false);

// A lone old-version rig in any composition is detected without a timeline selection.
const realProject = app.project;
const soloComp = solo.containingComp;
soloComp.list.forEach(l => { l.selected = false; });
solo.property('ADBE Effect Parade').effects = solo.property('ADBE Effect Parade').effects.filter(e => !['Rounded Corners', 'Corner Radius', 'Shuffle Images', 'Arrangement Seed'].includes(e.name));
app.project = {activeItem: null, numItems: 1, item: () => soloComp};
vm.runInContext(source, uiContext);
assert.equal(find('dropdownlist').selection.controller, solo);
assert.equal(find('checkbox', 'Rounded corners').value, false);
assert.equal(inputFor('Corner radius (px)').text, '24');
assert.equal(inputFor('Arrangement seed').text, '1');
app.project = {activeItem: null, numItems: 0, item: () => null};
solo.invalid = true;
find('button', 'Refresh').onClick();
assert.equal(find('dropdownlist').items.length, 1);
assert.equal(find('button', 'Update Carousel').enabled, false, 'Switching projects invalidates the old target');
assert.equal(find('listbox').items.length, 0);
app.project = realProject;

// Precomposed artwork is reused intact, including when Project selection takes activeItem.
const destination = app.project.items.addComp('Precomp destination', 800, 800, 1, 12, 30);
const artwork = app.project.items.addComp('Artwork precomp', 300, 200, 1, 2, 24);
artwork.parentFolder = originalFolder;
const innerLayer = artwork.layers.add(existing);
app.project.activeItem = destination;
vm.runInContext(source, uiContext);
const precompMenu = find('dropdownlist');
precompMenu.selection = precompMenu.items[0]; precompMenu.onChange();
app.project.selection = [artwork, existing, movie, originalFolder];
app.project.activeItem = artwork;
find('button', 'Use Project Selection').onClick();
find('button', 'Use Project Selection').onClick();
assert.equal(find('listbox').items.length, 2, 'Precomp selection filters unsupported items and deduplicates');
assert.match(find('listbox').items[0].text, /\[Comp\] Artwork precomp/);
const compImports = importCount;
find('button', 'Create Radial Carousel').onClick();
assert.equal(alerts.length, 0);
const precompCtrl = destination.list[0];
const artworkLayer = destination.list.find(l => l.parent === precompCtrl && l.source === artwork);
assert.ok(artworkLayer, 'Create uses the remembered destination, not the selected source precomp');
assert.equal(destination.numLayers, 3);
assert.equal(importCount, compImports, 'Precomps and project images are not imported again');
assert.equal(artwork.parentFolder, originalFolder);
assert.deepEqual(artwork.list, [innerLayer], 'Original precomp layers stay intact');
assert.equal(artwork.duration, 2);
assert.equal(artworkLayer.timeRemapEnabled, true);
near(artworkLayer.outPoint, destination.duration);
const remap = artworkLayer.property('ADBE Time Remapping').expression;
for (const time of [-1, 0, 0.5, 2, 11.9]) {
    near(vm.runInNewContext(remap, {time, startTime: 0, thisLayer: {source: artwork}}), Math.max(0, Math.min(time, 2 - 1 / 24)));
}
for (const duration of [12, 20]) {
    const longer = app.project.items.addComp('Long artwork', 200, 300, 1, duration, 30);
    const rig = api.build(s, [{item: longer, name: longer.name}], destination);
    const child = destination.list.find(l => l.parent === rig);
    assert.ok(!child.timeRemapEnabled, 'Equal/longer precomps keep normal playback');
    near(child.outPoint, destination.duration);
}

// Reopening recovers mixed comp/footage sources in their original order and updates both.
destination.list.forEach(l => { l.selected = false; });
artworkLayer.selected = true;
app.project.activeItem = destination;
vm.runInContext(source, uiContext);
assert.equal(find('dropdownlist').selection.controller, precompCtrl);
assert.equal(find('listbox').items.length, 2);
assert.match(find('listbox').items[0].text, /\[Comp\] Artwork precomp/);
const itemsBeforeUpdate = liveItems.length, layersBeforeUpdate = destination.numLayers;
artworkLayer.property('ADBE Mask Parade').effects = [];
find('checkbox', 'Rounded corners').value = true;
find('checkbox', 'Shuffle image order').value = true;
inputFor('Arrangement seed').text = '42';
find('button', 'Update Carousel').onClick();
assert.equal(alerts.length, 0);
const expressionContext = {parent: {effect: n => () => api.control(precompCtrl, n).value, transform: {rotation: 90}}, thisLayer: {source: artwork}, thisComp: destination};
const shape = vm.runInNewContext(artworkLayer.property('ADBE Mask Parade').property('RC Rounded Corners').property('ADBE Mask Shape').expression, {
    ...expressionContext, createPath: (points, ins, outs, closed) => ({points, closed})
});
assert.equal(shape.points.length, 8, 'Rounded mask updates on recovered precomp layers');
near(vm.runInNewContext(artworkLayer.property('ADBE Transform Group').property('ADBE Scale').expression, expressionContext)[0] * artwork.width / 100, api.control(precompCtrl, 'Image Size').value);
near(Math.hypot(...vm.runInNewContext(artworkLayer.property('ADBE Transform Group').property('ADBE Position').expression, expressionContext)), api.control(precompCtrl, 'Radius').value);
near(api.control(precompCtrl, 'Arrangement Seed').value, 42);
assert.equal(liveItems.length, itemsBeforeUpdate);
assert.equal(destination.numLayers, layersBeforeUpdate);
assert.equal(artworkLayer.property('ADBE Time Remapping').expression, remap);

// Reject direct and transitive comp cycles before any project/undo mutation.
const containsDestination = app.project.items.addComp('Contains destination', 100, 100, 1, 12, 30);
containsDestination.layers.add(destination);
const ancestor = app.project.items.addComp('Ancestor', 100, 100, 1, 12, 30);
ancestor.layers.add(containsDestination);
for (const item of [destination, containsDestination, ancestor]) {
    const itemCount = liveItems.length, layerCount = destination.numLayers;
    assert.throws(() => api.build(s, [{item, name: item.name}], destination), /inside itself/);
    assert.equal(liveItems.length, itemCount);
    assert.equal(destination.numLayers, layerCount);
    assert.equal(app.undoDepth, 0);
}
artwork.invalid = true;
assert.throws(() => api.build(s, [{item: artwork, name: artwork.name}], destination), /unavailable/);
artwork.invalid = false;
const beforeCompFailure = liveItems.length;
assert.throws(() => api.build(s, [{item: artwork, name: artwork.name}, {...files[0], bad: true}], destination));
assert.equal(liveItems.length, beforeCompFailure);
assert.equal(artwork.parentFolder, originalFolder);
assert.deepEqual(artwork.list, [innerLayer]);

// Opening the panel on the artwork itself offers a clear error; a new comp is valid.
app.project.activeItem = artwork;
vm.runInContext(source, uiContext);
find('dropdownlist').selection = find('dropdownlist').items[0]; find('dropdownlist').onChange();
app.project.selection = [artwork];
find('button', 'Use Project Selection').onClick();
find('button', 'Create Radial Carousel').onClick();
assert.match(alerts.pop(), /inside itself/);
find('checkbox', 'Add to the active composition').value = false;
find('button', 'Create Radial Carousel').onClick();
assert.equal(alerts.length, 0);
assert.notEqual(app.project.activeItem, artwork);
assert.ok(app.project.activeItem.list.some(l => l.source === artwork));

// A native failure must keep its source/step/line through rollback and the GUI catch.
find('dropdownlist').selection = find('dropdownlist').items[0]; find('dropdownlist').onChange();
find('button', 'Use Project Selection').onClick();
const realAddComp = app.project.items.addComp;
const beforeNativeFailure = liveItems.length;
app.project.items.addComp = (...args) => {
    const result = realAddComp(...args);
    const add = result.layers.add;
    result.layers.add = item => {
        if (item === artwork) {
            const error = new Error('null is not an object'); error.line = 321; throw error;
        }
        return add(item);
    };
    return result;
};
find('button', 'Create Radial Carousel').onClick();
app.project.items.addComp = realAddComp;
const diagnostic = alerts.pop();
assert.match(diagnostic, /Radial Carousel 1\.6\.5/);
assert.match(diagnostic, /Action: Create Radial Carousel/);
assert.match(diagnostic, /Step: Add carousel layer 1: Artwork precomp/);
assert.match(diagnostic, /Line: 321/);
assert.match(diagnostic, /null is not an object/);
assert.equal(liveItems.length, beforeNativeFailure, 'Diagnostics preserve creation rollback');
assert.equal(app.undoDepth, 0);
// Run the same recovery cases that can be run independently in native ExtendScript.
const recoveryFile = path.join(__dirname, 'Recovery Test.jsx');
class RecoveryFile {
    constructor(file) { this.fsName = file; this.parent = {fsName: path.dirname(file)}; }
    open() { return fs.existsSync(this.fsName); }
    read() { return fs.readFileSync(this.fsName, 'utf8'); }
    close() {}
}
let recoveryResult;
vm.runInNewContext(fs.readFileSync(recoveryFile, 'utf8'), {
    File: RecoveryFile, $: {fileName: recoveryFile}, alert: result => { recoveryResult = result; }
});
assert.match(recoveryResult, /^PASS: 5 recovery checks/);

// Unfolded Orbit: evaluate the shipped expressions with their actual dependencies.
const orbitSettings = {...s, orbit: true, orbitClockwise: false, unfold: 0.8, zoomTime: 1.15,
    hold: 0.8, transition: 0.6, zoom: 280, blur: 18, sideScale: 50, duration: 17};
function orbitSample(rig, layer, name, time, slot) {
    const effect = n => () => {
        const p = api.control(rig, n);
        if (!p.expression) return p.value;
        return vm.runInNewContext(p.expression, {effect, time, inPoint: rig.inPoint});
    };
    const rotation = vm.runInNewContext(rig.property('ADBE Transform Group').property('ADBE Rotate Z').expression,
        {effect, time, inPoint: rig.inPoint, value: 0});
    const scale = vm.runInNewContext(rig.property('ADBE Transform Group').property('ADBE Scale').expression,
        {effect, value: [100, 100]});
    const layerScale = vm.runInNewContext(layer.property('ADBE Transform Group').property('ADBE Scale').expression,
        {parent: {effect}, thisLayer:{source:layer.source}, thisComp:rig.containingComp});
    const p = name === 'blur' ? layer.property('ADBE Effect Parade').property('RC Focus Blur').property(1) : layer.property('ADBE Transform Group').property(name);
    const expression = slot === undefined ? p.expression : p.expression.replace(/var slot = \d+, n =/, 'var slot = '+slot+', n =');
    return vm.runInNewContext(expression, {parent: {effect, transform: {rotation, scale}}, thisLayer: {source: layer.source, transform: {scale: layerScale}},
        thisComp: rig.containingComp, value: 100});
}
for (const halfCircle of [false, true]) {
for (const n of [1, 2, 3, 8, 12]) {
    const shapeSettings = {...orbitSettings, halfCircle};
    const inputs = Array.from({length: n}, (_,i) => ({...files[i%files.length], name: 'Card '+i}));
    const rig = api.build(shapeSettings, inputs, null);
    const cards = rig.containingComp.list.filter(l=>l.parent === rig).reverse();
    const length = api.orbitDuration(orbitSettings, n);
    if (n===8) near(length, 17);
    for (const reverse of [false, true]) {
        api.configure(rig, {...shapeSettings, orbitClockwise: reverse});
        for (let i=0;i<n;i++) {
            const focusIndex = reverse ? (n-i)%n : i;
            const time = 2.5 + i*1.4 + 0.4;
            const pos = orbitSample(rig,cards[focusIndex],'ADBE Position',time);
            near(pos[0],0); near(pos[1],0);
            near(orbitSample(rig,cards[focusIndex],'blur',time),0);
            const focusedScale=orbitSample(rig,cards[focusIndex],'ADBE Scale',time)[0];
            near(focusedScale*Math.max(cards[focusIndex].source.width*cards[focusIndex].source.pixelAspect,cards[focusIndex].source.height)/100,160);
        }
        for (let i=0;i<n;i++) {
            near(orbitSample(rig,cards[i],'ADBE Opacity',0),i===0?100:0);
            for (const property of ['ADBE Position','ADBE Opacity','blur','ADBE Rotate Z']) {
                const start = [].concat(orbitSample(rig,cards[i],property,0));
                const end = [].concat(orbitSample(rig,cards[i],property,length));
                start.forEach((v,j)=>near(v,end[j]));
            }
            const ring = orbitSample(rig,cards[i],'ADBE Position',1.2);
            near(Math.hypot(...ring),orbitSettings.radius);
            const angle = (-90 + i * (halfCircle && n > 1 ? 180/(n-1) : 360/n)) * Math.PI/180;
            near(ring[0], 240*Math.cos(angle)); near(ring[1], 240*Math.sin(angle));
            near(orbitSample(rig,cards[i],'blur',1.2),0);
            if(i && n>1) {
                assert.ok(orbitSample(rig,cards[i],'blur',2.9)>0);
                const side=orbitSample(rig,cards[i],'ADBE Scale',2.9)[0];
                near(side*Math.max(cards[i].source.width*cards[i].source.pixelAspect,cards[i].source.height)/100,80);
            }
        }
    }
    for (const t of [-0.01,0,0.3,1.1,1.35,2.5,length-1.35,length-1.1,length-0.3,length]) {
        const left = api.orbitState(t-1e-7,n,0.8,1.15,0.8,0.6);
        const right = api.orbitState(t+1e-7,n,0.8,1.15,0.8,0.6);
        near(left[0],right[0]); near(left[1],right[1]);
        near(Math.sin(left[2]*Math.PI*2),Math.sin(right[2]*Math.PI*2));
    }
    const counts = cards.map(l=>l.property('ADBE Effect Parade').effects.length);
    api.configure(rig, {...shapeSettings, orbit:false});
    cards.forEach((l,i)=>{near(Math.hypot(...orbitSample(rig,l,'ADBE Position',4)),240);near(orbitSample(rig,l,'blur',4),0);near(orbitSample(rig,l,'ADBE Opacity',0),100);assert.equal(l.property('ADBE Effect Parade').effects.length,counts[i]);});
}
}
// Real panel flow: choose mode, create, reopen, update, reject a truncated loop.
vm.runInContext(source,uiContext);
find('dropdownlist').selection = find('dropdownlist').items[0]; find('dropdownlist').onChange();
const animationMenu = find('statictext','Animation').parent.children.find(c=>c.type==='dropdownlist');
animationMenu.selection = animationMenu.items[1]; animationMenu.onChange();
find('checkbox','Add to the active composition').value = false;
app.project.selection = [artwork,existing]; find('button','Use Project Selection').onClick();
find('button','Create Radial Carousel').onClick();
assert.equal(alerts.length,0);
const orbitComp = app.project.activeItem, orbitCtrl = orbitComp.list[0];
near(orbitComp.duration, Math.ceil(api.orbitDuration(orbitSettings,2)*30)/30);
near(api.control(orbitCtrl,'Unfolded Orbit').value,1);
const orbitCount = orbitComp.numLayers, orbitEffects = orbitCtrl.property('ADBE Effect Parade').effects.length;
vm.runInContext(source,uiContext);
assert.equal(orbitCtrl.property('ADBE Effect Parade').effects.length,orbitEffects,'Reopening remains read only');
const reopenedMode = find('statictext','Animation').parent.children.find(c=>c.type==='dropdownlist');
assert.equal(reopenedMode.selection,reopenedMode.items[1]);
find('statictext','Focus blur (px)').parent.children.find(c=>c.type==='edittext').text = '27';
find('button','Update Carousel').onClick();
near(api.control(orbitCtrl,'Focus Blur').value,27);
assert.equal(orbitComp.numLayers,orbitCount,'Update does not duplicate cards');
find('statictext','Hold per image (s)').parent.children.find(c=>c.type==='edittext').text = '60';
find('button','Update Carousel').onClick();
assert.match(alerts.pop(),/full Unfolded Orbit loop needs/);
near(api.control(orbitCtrl,'Image Hold').value,0.8);
find('statictext','Hold per image (s)').parent.children.find(c=>c.type==='edittext').text = '-1';
find('button','Update Carousel').onClick();
assert.match(alerts.pop(),/Hold per image/);
assert.equal(app.undoDepth,0);
// An older short rig must cover the complete loop after its comp is lengthened.
const shortSource=track(new CompItem('Short orbit source',800,600,1,4,30));
const shortRig=api.build({...s,duration:4},[{item:shortSource,name:shortSource.name}],null);
const shortCard=shortRig.containingComp.list.find(l=>l.parent===shortRig);
shortRig.containingComp.duration=17; shortRig.inPoint=1;
api.configure(shortRig,orbitSettings);
near(shortRig.outPoint,1+api.orbitDuration(orbitSettings,1));
near(shortCard.outPoint,shortRig.outPoint);
assert.equal(shortCard.timeRemapEnabled,true);
near(shortSource.duration,4);
// A shifted controller also needs room after its in point; rejection precedes writes.
find('statictext','Hold per image (s)').parent.children.find(c=>c.type==='edittext').text='0.8';
orbitCtrl.inPoint=2;
find('button','Update Carousel').onClick();
assert.match(alerts.pop(),/from the controller's in point/);
console.log('PASS: Unfolded Orbit with 180/360 arcs, loop boundaries, all-card focus order, both directions, 1/2/3/8/12 cards, blur, opacity, mode switching, recovery, updates, and timing validation.');
// Half-circle geometry uses both endpoints; full circles never duplicate the first slot.
function arcSample(rig, layer, property, rotation = 0, slot) {
    let expression = layer.property('ADBE Transform Group').property(property).expression;
    if (slot !== undefined) expression = expression.replace(/var slot = \d+, n =/, 'var slot = '+slot+', n =');
    return vm.runInNewContext(expression, {
        parent: {effect: name => () => api.control(rig, name).value, transform: {rotation}}
    });
}
for (const n of [1, 2, 3, 8]) {
    const inputs = Array.from({length: n}, (_, i) => ({...files[i % files.length], name: 'Arc ' + i}));
    const rig = api.build({...s, halfCircle: true}, inputs, null);
    const cards = rig.containingComp.list.filter(l => l.parent === rig).reverse();
    const effectCount = rig.property('ADBE Effect Parade').effects.length;
    for (const halfCircle of [true, false, true]) {
        for (const angle of [-180, -90, 0, 90]) {
            for (const shuffle of [false, true]) {
                for (const upright of [false, true]) {
                    api.configure(rig, {...s, halfCircle, angle, shuffle, seed: 42, upright, offset: 12});
                    const expected = Array.from({length: n}, (_, i) => {
                        const a = (angle + i * (halfCircle ? 180 / Math.max(1, n - 1) : 360 / n)) * Math.PI / 180;
                        return [s.radius * Math.cos(a), s.radius * Math.sin(a)];
                    });
                    const actual = cards.map(l => Array.from(arcSample(rig, l, 'ADBE Position')));
                    assert.equal(new Set(actual.map(p => p.map(v => v.toFixed(5)).join(','))).size, n);
                    actual.forEach((p, i) => {
                        const target = shuffle ? expected.find(q => Math.hypot(p[0]-q[0], p[1]-q[1]) < 1e-7) : expected[i];
                        assert.ok(target, 'Shuffling only permutes the arc slots');
                        near(p[0], target[0]); near(p[1], target[1]);
                        for (const rotation of [-45, 0, 45]) {
                            const r = arcSample(rig, cards[i], 'ADBE Rotate Z', rotation);
                            if (upright) near(r + rotation, 12);
                            else {
                                near(Math.cos((r-102)*Math.PI/180), p[0]/s.radius);
                                near(Math.sin((r-102)*Math.PI/180), p[1]/s.radius);
                            }
                        }
                    });
                }
            }
        }
    }
    assert.equal(rig.containingComp.numLayers, n + 1);
    assert.equal(rig.property('ADBE Effect Parade').effects.length, effectCount);
}

// Recover published v1.3-v1.5 rigs without mutating them until Update; retain source order.
const arcRig = api.build(s, files, null);
const arcCards = arcRig.containingComp.list.filter(l => l.parent === arcRig).reverse();
const arcEffects = arcRig.property('ADBE Effect Parade');
arcEffects.effects = arcEffects.effects.filter(e => e.name !== 'Half Circle');
for (const layer of arcCards) {
    for (const name of ['ADBE Position', 'ADBE Rotate Z']) {
        const p = layer.property('ADBE Transform Group').property(name);
        p.expression = p.expression.replace(/var step = 360 \/ n;\n[^\n]+\n[^\n]+\n/,
            'var a = parent.effect("Start Angle")(1) + 360 * slot / n;\n');
    }
}
app.project.activeItem = arcRig.containingComp;
const beforeArcLoad = arcEffects.effects.length;
const beforeArcExpressions = arcCards.map(l => l.property('ADBE Transform Group').property('ADBE Position').expression);
vm.runInContext(source, uiContext);
const arcMenu = () => find('statictext', 'Arc').parent.children.find(c => c.type === 'dropdownlist');
assert.equal(arcMenu().selection, arcMenu().items[0]);
assert.equal(arcEffects.effects.length, beforeArcLoad, 'Opening an old rig adds no arc control');
assert.deepEqual(arcCards.map(l => l.property('ADBE Transform Group').property('ADBE Position').expression), beforeArcExpressions);
arcMenu().selection = arcMenu().items[1];
find('button', 'Update Carousel').onClick();
assert.equal(alerts.length, 0);
near(api.control(arcRig, 'Half Circle').value, 1);
arcCards.forEach((l, i) => {
    const p = arcSample(arcRig, l, 'ADBE Position');
    near(p[0], s.radius * Math.cos((-90+i*90)*Math.PI/180));
    near(p[1], s.radius * Math.sin((-90+i*90)*Math.PI/180));
});
vm.runInContext(source, uiContext);
assert.equal(arcMenu().selection, arcMenu().items[1], 'Reopening restores Half circle');
assert.equal(find('listbox').items.length, files.length);
// Pre-shuffle v1.0-v1.2 expressions also upgrade to a half circle, preserving order.
for (const [i, l] of arcCards.entries()) {
    for (const name of ['ADBE Position', 'ADBE Rotate Z']) {
        const p = l.property('ADBE Transform Group').property(name);
        p.expression = p.expression.replace(/^[\s\S]*?var a = [^\n]+\n/,
            'var a = parent.effect("Start Angle")(1) + ' + i * 120 + ';\n');
    }
}
api.configure(arcRig, {...s, halfCircle: true});
arcCards.forEach((l, i) => {
    const p = arcSample(arcRig, l, 'ADBE Position');
    near(p[0], s.radius * Math.cos((-90+i*90)*Math.PI/180));
    near(p[1], s.radius * Math.sin((-90+i*90)*Math.PI/180));
});
const arcControl = api.control(arcRig, 'Half Circle');
arcControl.numKeys = 2; arcRig.containingComp.time = 4;
arcMenu().selection = arcMenu().items[0];
find('button', 'Update Carousel').onClick();
assert.deepEqual(Array.from(arcControl.lastKey), [4, 0], 'Updating keyed arc inserts at the playhead');
assert.equal(arcEffects.effects.length, beforeArcLoad + 1);

// Creation callback saves the chosen arc, including a single-image carousel.
find('dropdownlist').selection = find('dropdownlist').items[0]; find('dropdownlist').onChange();
arcMenu().selection = arcMenu().items[1];
find('checkbox', 'Add to the active composition').value = false;
app.project.selection = [existing]; find('button', 'Use Project Selection').onClick();
find('button', 'Create Radial Carousel').onClick();
assert.equal(alerts.length, 0);
near(api.control(app.project.activeItem.list[0], 'Half Circle').value, 1);
assert.equal(app.project.activeItem.numLayers, 2);

console.log('PASS: 180/360 geometry, endpoints, single image, orientations, shuffle, old-rig upgrade, create/update/reopen, and keyed arc controls.');
// Measure added spacing from the generated positions, independent of the radius formula.
const distance = (a, b) => Math.hypot(a[0]-b[0], a[1]-b[1]);
for (const halfCircle of [false, true]) for (const n of [1, 2, 3, 8]) {
    const inputs = Array.from({length:n}, (_,i)=>({...files[i%files.length], name:'Gap '+i}));
    for (const orbit of [false, true]) {
        const settings = {...orbitSettings, halfCircle, orbit};
        const rig = api.build(settings, inputs, null);
        const cards = rig.containingComp.list.filter(l=>l.parent===rig).reverse();
        const sample = (card, time=1.2) => orbit ? orbitSample(rig,card,'ADBE Position',time) : arcSample(rig,card,'ADBE Position');
        const baseline = cards.map(card=>sample(card));
        for (const gap of [24, 64, 0]) {
            api.configure(rig, {...settings, gap});
            const positions = cards.map(card=>sample(card));
            near(api.control(rig,'Radius').value, settings.radius);
            near(api.control(rig,'Image Size').value, settings.size);
            for (let i=0;i<n;i++) {
                if (n===1 || gap===0) { near(positions[i][0],baseline[i][0]); near(positions[i][1],baseline[i][1]); }
                if (i) near(distance(positions[i-1],positions[i])-distance(baseline[i-1],baseline[i]),gap);
                if (!halfCircle && n>1 && i===n-1) near(distance(positions[i],positions[0])-distance(baseline[i],baseline[0]),gap);
                const scale = orbit ? orbitSample(rig,cards[i],'ADBE Scale',1.2) : vm.runInNewContext(cards[i].property('ADBE Transform Group').property('ADBE Scale').expression,
                    {parent:{effect:name=>()=>api.control(rig,name).value},thisLayer:{source:cards[i].source},thisComp:rig.containingComp});
                near(scale[0]*Math.max(cards[i].source.width*cards[i].source.pixelAspect,cards[i].source.height)/100,settings.size);
            }
            if (orbit) for (const reverse of [false,true]) {
                api.control(rig,'Orbit Clockwise').setValue(reverse?1:0);
                for (let i=0;i<n;i++) {
                    const card=cards[reverse?(n-i)%n:i], time=2.9+i*1.4;
                    const focus=sample(card,time); near(focus[0],0); near(focus[1],0);
                    near(orbitSample(rig,card,'blur',time),0);
                    const end=sample(card,api.orbitDuration(settings,n)), start=sample(card,0);
                    near(end[0],start[0]); near(end[1],start[1]);
                }
            }
        }
    }
}
// Published rigs do not gain effects on opening. Update installs Gap once and preserves sources.
for (const legacyRadius of [false,true]) {
    const rig=api.build({...s,halfCircle:true},files,null);
    const cards=rig.containingComp.list.filter(l=>l.parent===rig).reverse();
    const effects=rig.property('ADBE Effect Parade');
    effects.effects=effects.effects.filter(e=>e.name!=='Gap');
    for (const card of cards) {
        const p=card.property('ADBE Transform Group').property('ADBE Position');
        p.expression=p.expression.replace(/^if \(n > 1\) \{ r \+= [^\n]+\n/m,'');
        if (legacyRadius) p.expression=p.expression.replace('var r = Math.max(0, parent.effect("Radius")(1));\n','var r = parent.effect("Radius")(1); ');
    }
    const baseline=cards.map(c=>arcSample(rig,c,'ADBE Position'));
    app.project.activeItem=rig.containingComp;
    const count=effects.effects.length, expressions=cards.map(c=>c.property('ADBE Transform Group').property('ADBE Position').expression);
    vm.runInContext(source,uiContext);
    assert.equal(inputFor('Gap (px)').text,'0');
    assert.equal(effects.effects.length,count);
    assert.deepEqual(cards.map(c=>c.property('ADBE Transform Group').property('ADBE Position').expression),expressions);
    inputFor('Gap (px)').text='36.5'; find('button','Update Carousel').onClick();
    find('button','Update Carousel').onClick();
    assert.equal(alerts.length,0); assert.equal(effects.effects.length,count+1);
    near(distance(arcSample(rig,cards[0],'ADBE Position'),arcSample(rig,cards[1],'ADBE Position'))-distance(baseline[0],baseline[1]),36.5);
    vm.runInContext(source,uiContext);
    assert.equal(inputFor('Gap (px)').text,'36.5');
    for (const value of ['-1','Infinity','abc','30001','']) {
        inputFor('Gap (px)').text=value; find('button','Update Carousel').onClick();
        assert.match(alerts.pop(),/Gap/); near(api.control(rig,'Gap').value,36.5);
    }
    const prop=api.control(rig,'Gap'); prop.numKeys=2; rig.containingComp.time=3;
    inputFor('Gap (px)').text='48'; find('button','Update Carousel').onClick();
    assert.deepEqual(Array.from(prop.lastKey),[3,48]); assert.equal(prop.numKeys,2);
    assert.equal(rig.containingComp.numLayers,4); assert.equal(app.undoDepth,0);
}
// Actual creation callback persists the chosen gap.
find('dropdownlist').selection=find('dropdownlist').items[0]; find('dropdownlist').onChange();
inputFor('Gap (px)').text='40';
find('checkbox','Add to the active composition').value=false;
app.project.selection=[existing]; find('button','Use Project Selection').onClick();
find('button','Create Radial Carousel').onClick(); assert.equal(alerts.length,0);
near(api.control(app.project.activeItem.list[0],'Gap').value,40);
console.log('PASS: Gap measured spacing, unchanged image size, zero/single image, both arcs and modes/directions, focus/loop, old-rig upgrade, create/update/reopen, validation, and keyed controls.');
// Render the source center through Anchor/Scale/Rotation/Position and its parent.
// Checking Position alone misses anchor compensation and the visible end-card crowding.
function rendered(rig, card, time = 1.2, slot, parentRotation) {
    const effect = name => () => {
        const p = api.control(rig,name);
        return p.expression ? vm.runInNewContext(p.expression,{effect,time,inPoint:rig.inPoint}) : p.value;
    };
    const root = rig.property('ADBE Transform Group');
    const pr = parentRotation === undefined ? vm.runInNewContext(root.property('ADBE Rotate Z').expression,
        {effect,time,inPoint:rig.inPoint,value:0}) : parentRotation;
    const env = {parent:{effect,transform:{rotation:pr}},thisLayer:{source:card.source},thisComp:rig.containingComp};
    const sample = name => {
        const p = card.property('ADBE Transform Group').property(name);
        let expr = p.expression;
        if (slot !== undefined) expr = expr.replace(/var slot = \d+, n =/,'var slot = '+slot+', n =');
        return expr ? vm.runInNewContext(expr,env) : p.value;
    };
    const p = sample('ADBE Position'), scale = sample('ADBE Scale'), rotation = sample('ADBE Rotate Z');
    env.transform = {position:p,scale,rotation};
    const anchor = sample('ADBE Anchor Point');
    const x = (card.source.width/2-anchor[0])*scale[0]/100*card.source.pixelAspect/rig.containingComp.pixelAspect;
    const y = (card.source.height/2-anchor[1])*scale[1]/100, a = rotation*Math.PI/180;
    const local = [p[0]+x*Math.cos(a)-y*Math.sin(a),p[1]+x*Math.sin(a)+y*Math.cos(a)];
    const t = pr*Math.PI/180;
    return {p:[local[0]*Math.cos(t)-local[1]*Math.sin(t),local[0]*Math.sin(t)+local[1]*Math.cos(t)],rotation:rotation+pr,anchor,scale};
}
// Circular bows preserve endpoints, equal spacing, and image dimensions.
for (const halfCircle of [false,true]) for (const n of [1,2,5]) for (const angle of [-180,30]) {
    const inputs=Array.from({length:n},(_,i)=>({...files[i%files.length],name:'Bend '+i}));
    for (const orbit of [false,true]) {
        const settings={...orbitSettings,halfCircle,angle,orbit,gap:40,upright:false,offset:12};
        const rig=api.build(settings,inputs,null), cards=rig.containingComp.list.filter(l=>l.parent===rig).reverse();
        const sample=(card,t=1.2)=>rendered(rig,card,t,undefined,0).p;
        const baseline=cards.map(c=>sample(c)), axis=angle*Math.PI/180;
        const across=p=>p[0]*Math.cos(axis)+p[1]*Math.sin(axis);
        const depth=p=>-p[0]*Math.sin(axis)+p[1]*Math.cos(axis);
        for (const bend of [0,35,100,200]) {
            api.configure(rig,{...settings,bend});
            for (const [i,card] of cards.entries()) {
                const p=sample(card);
                if (halfCircle && n>1) {
                    const r=settings.radius+settings.gap/(2*Math.sin(Math.PI/(2*(n-1))));
                    if (bend===0) { near(across(p),r*(1-2*i/(n-1))); near(depth(p),0); }
                    else {
                        const b=bend/100, center=r*(b*b-1)/(2*b), radius=r*(1+b*b)/(2*b);
                        near(Math.hypot(across(p),depth(p)-center),radius);
                    }
                    if (i>1) {
                        const p1=sample(cards[i-1]),p2=sample(cards[i-2]);
                        near(Math.hypot(p[0]-p1[0],p[1]-p1[1]),Math.hypot(p1[0]-p2[0],p1[1]-p2[1]));
                    }
                }
                if (!halfCircle || n===1 || i===0 || i===n-1 || bend===100) {
                    near(p[0],baseline[i][0]); near(p[1],baseline[i][1]);
                }
                if (orbit) {
                    const size=orbitSample(rig,card,'ADBE Scale',1.2)[0];
                    near(size*Math.max(card.source.width*card.source.pixelAspect,card.source.height)/100,settings.size);
                }
                checkTangent(rig,card,i,settings,bend,1.2);
            }
            if (orbit && halfCircle) for (const reverse of [false,true]) {
                api.control(rig,'Orbit Clockwise').setValue(reverse?1:0);
                for(let i=0;i<n;i++){
                    const card=cards[reverse?(n-i)%n:i], t=2.9+i*1.4, focus=sample(card,t);
                    near(focus[0],0);near(focus[1],0);near(orbitSample(rig,card,'blur',t),0);
                    const start=sample(card,0),end=sample(card,api.orbitDuration(settings,n));
                    near(start[0],end[0]);near(start[1],end[1]);
                }
            }
            api.configure(rig,{...settings,bend,upright:true});
            for(const card of cards) near(orbit?orbitSample(rig,card,'ADBE Rotate Z',3.6):arcSample(rig,card,'ADBE Rotate Z',23),orbit?settings.offset:-23+settings.offset);
        }
    }
}
// Compare orientation with a finite difference of the generated Position expression.
// This checks the actual curve independently of the rotation formula.
function checkTangent(rig,card,slot,settings,bend,time) {
    const rotation=rendered(rig,card,time,undefined,0).rotation;
    const radians=(rotation-settings.offset)*Math.PI/180;
    const point=s=>rendered(rig,card,time,s,0).p;
    const before=point(slot-0.0001), after=point(slot+0.0001);
    const dx=after[0]-before[0],dy=after[1]-before[1],length=Math.hypot(dx,dy);
    near(Math.cos(radians),dx/length);near(Math.sin(radians),dy/length);
}
// Still images and precomp layers follow the bend during animated travel in either direction.
for (const halfCircle of [false,true]) for (const reverse of [false,true]) {
    const settings={...orbitSettings,halfCircle,orbitClockwise:reverse,upright:false,angle:-135,offset:17};
    const rig=api.build(settings,[{item:existing},{item:artwork},...files],null);
    const cards=rig.containingComp.list.filter(c=>c.parent===rig).reverse();
    assert.equal(cards[0].source,existing);assert.equal(cards[1].source,artwork);
    for (const bend of [0,25,100,200]) {
        api.configure(rig,{...settings,bend});
        for (const time of [1.8,2.1,3.6,5]) for (const [i,card] of cards.entries()) checkTangent(rig,card,i,settings,bend,time);
    }
}
// Migrate pre-Bend generated expressions without rewriting source order or creating on load.
for (const legacy of [false,true]) {
    const rig=api.build({...s,halfCircle:true,upright:false,angle:-180},files,null);
    const cards=rig.containingComp.list.filter(l=>l.parent===rig).reverse(), effects=rig.property('ADBE Effect Parade');
    effects.effects=effects.effects.filter(e=>e.name!=='Bend');
    for(const [i,card] of cards.entries()){
        const tr=card.property('ADBE Transform Group');
        const header=legacy?'var a = parent.effect("Start Angle")(1) + '+i*120+';\n':tr.property('ADBE Position').expression.split('var r =')[0];
        tr.property('ADBE Position').expression=header+'var r = parent.effect("Radius")(1); var rad = a*Math.PI/180; [r * Math.cos(rad), r * Math.sin(rad)];';
        tr.property('ADBE Rotate Z').expression=header+'parent.effect("Keep Upright")(1) > 0.5 ? -parent.transform.rotation : a + 90;';
    }
    app.project.activeItem=rig.containingComp;
    const original=cards.map(c=>c.property('ADBE Transform Group').property('ADBE Position').expression), count=effects.effects.length;
    vm.runInContext(source,uiContext);
    assert.equal(inputFor('Bend (%)').text,'100');assert.equal(inputFor('Bend (%)').enabled,true);
    assert.equal(effects.effects.length,count);assert.deepEqual(cards.map(c=>c.property('ADBE Transform Group').property('ADBE Position').expression),original);
    inputFor('Bend (%)').text='25';find('button','Update Carousel').onClick();
    find('button','Update Carousel').onClick();assert.equal(alerts.length,0);assert.equal(effects.effects.length,count+1);
    const middle=arcSample(rig,cards[1],'ADBE Position');near(middle[0],0);near(middle[1],-60);
    const upgraded=cards.map(c=>c.property('ADBE Transform Group').property('ADBE Position').expression);
    vm.runInContext(source,uiContext);assert.equal(inputFor('Bend (%)').text,'25');
    assert.deepEqual(cards.map(c=>c.property('ADBE Transform Group').property('ADBE Position').expression),upgraded);
    for(const value of ['-1','201','NaN','Infinity','']){
        inputFor('Bend (%)').text=value;find('button','Update Carousel').onClick();
        assert.match(alerts.pop(),/Bend/);near(api.control(rig,'Bend').value,25);assert.equal(app.undoDepth,0);
    }
    arcMenu().selection=arcMenu().items[0];arcMenu().onChange();assert.equal(inputFor('Bend (%)').enabled,false);
    find('button','Update Carousel').onClick();assert.equal(alerts.length,0);near(api.control(rig,'Bend').value,100);
    arcMenu().selection=arcMenu().items[1];arcMenu().onChange();assert.equal(inputFor('Bend (%)').enabled,true);
    const prop=api.control(rig,'Bend');prop.numKeys=2;rig.containingComp.time=5;
    inputFor('Bend (%)').text='40';find('button','Update Carousel').onClick();
    assert.deepEqual(Array.from(prop.lastKey),[5,40]);assert.equal(prop.numKeys,2);assert.equal(rig.containingComp.numLayers,4);
}
// Update the previous local Bend rotation block and persist either orientation in both modes.
for (const orbit of [false,true]) {
    const rig=api.build({...orbitSettings,orbit,halfCircle:true,bend:25,upright:false},[{item:existing},{item:artwork},...files],null);
    const cards=rig.containingComp.list.filter(c=>c.parent===rig).reverse();
    const positions=cards.map(c=>c.property('ADBE Transform Group').property('ADBE Position').expression);
    for (const card of cards) {
        const tr=card.property('ADBE Transform Group');
        const oldBend=tr.property('ADBE Position').expression.match(/\/\/ RC bend\nfunction rcBend\(p\) \{[\s\S]*?\n\}\n/)[0] +
            'var original = a * Math.PI / 180, direction = rcBend([Math.cos(original), Math.sin(original)]);\n' +
            'if (direction[0]*direction[0] + direction[1]*direction[1] > 0.000000000001) {\n' +
            '  a += Math.atan2(direction[1]*Math.cos(original)-direction[0]*Math.sin(original),\n' +
            '    direction[0]*Math.cos(original)+direction[1]*Math.sin(original)) * 180 / Math.PI;\n}\n';
        tr.property('ADBE Rotate Z').expression=orbit?'var offset = parent.effect("Image Rotation Offset")(1);\n-parent.transform.rotation + offset;':
            tr.property('ADBE Rotate Z').expression.replace(/\/\/ RC bend rotation[\s\S]*?\n\}\n/,oldBend);
    }
    app.project.activeItem=rig.containingComp;vm.runInContext(source,uiContext);
    assert.equal(find('radiobutton','Follow arc / bend').value,true);
    assert.equal(find('radiobutton','Follow arc / bend').enabled,true);
    assert.equal(find('radiobutton','Keep images upright while orbiting').enabled,true);
    find('button','Update Carousel').onClick();find('button','Update Carousel').onClick();
    assert.equal(alerts.length,0);
    assert.deepEqual(cards.map(c=>c.property('ADBE Transform Group').property('ADBE Position').expression),positions);
    assert.equal(cards[0].source,existing);assert.equal(cards[1].source,artwork);
    for (const [i,card] of cards.entries()) {
        const expression=card.property('ADBE Transform Group').property('ADBE Rotate Z').expression;
        assert.equal(expression.split('// RC bend rotation').length,2);assert.doesNotMatch(expression,/var original/);
        checkTangent(rig,card,i,{...orbitSettings,orbit,halfCircle:true},25,3.6);
    }
    find('radiobutton','Keep images upright while orbiting').value=true;
    find('radiobutton','Follow arc / bend').value=false;find('button','Update Carousel').onClick();
    near(api.control(rig,'Keep Upright').value,1);
    vm.runInContext(source,uiContext);assert.equal(find('radiobutton','Keep images upright while orbiting').value,true);
    find('radiobutton','Follow arc / bend').value=true;
    find('radiobutton','Keep images upright while orbiting').value=false;find('button','Update Carousel').onClick();
    near(api.control(rig,'Keep Upright').value,0);
    vm.runInContext(source,uiContext);assert.equal(find('radiobutton','Follow arc / bend').value,true);
}
find('dropdownlist').selection=find('dropdownlist').items[0];find('dropdownlist').onChange();
arcMenu().selection=arcMenu().items[1];arcMenu().onChange();inputFor('Bend (%)').text='60';
find('checkbox','Add to the active composition').value=false;
app.project.selection=[existing];find('button','Use Project Selection').onClick();find('button','Create Radial Carousel').onClick();
assert.equal(alerts.length,0);near(api.control(app.project.activeItem.list[0],'Bend').value,60);
// Screenshot regression: a shallow, rotating 12-card bow must retain equal gaps and
// a single curvature center, with a finite, continuous limit through Bend 0.
for (const orbit of [false,true]) {
    const settings={...orbitSettings,orbit,halfCircle:true,angle:-180,radius:3200,size:768,gap:0,speed:-1,upright:false};
    const rig=api.build(settings,Array.from({length:12},(_,i)=>files[i%files.length]),null);
    const cards=rig.containingComp.list.filter(c=>c.parent===rig).reverse();
    for (const bend of [0,0.000001,0.1,25,50,99.999,100,100.001,200]) {
        api.configure(rig,{...settings,bend});
        for (const time of [0,1.2,1.8,3.5,8,15]) {
            const points=cards.map(c=>rendered(rig,c,time));
            const separation=Math.hypot(points[1].p[0]-points[0].p[0],points[1].p[1]-points[0].p[1]);
            for (let i=0;i<cards.length;i++) {
                assert.ok([...points[i].p,...points[i].anchor,points[i].rotation].every(Number.isFinite));
                near(points[i].scale[0],points[i].scale[1]);
                if (i>1) near(Math.hypot(points[i].p[0]-points[i-1].p[0],points[i].p[1]-points[i-1].p[1]),separation);
            }
            if (!orbit && bend>0.1) {
                const b=bend/100,cy=3200*(1-b*b)/(2*b),radius=3200*(1+b*b)/(2*b);
                for (const p of points) {
                    near(Math.hypot(p.p[0],p.p[1]-cy),radius);
                    const a=p.rotation*Math.PI/180;
                    near((Math.cos(a)*p.p[0]+Math.sin(a)*(p.p[1]-cy))/radius,0);
                }
            }
        }
    }
    // Sub-frame/small-Bend changes must not flip endpoint rotations or move centers suddenly.
    for (const time of [0,1.2,3.5,15]) {
        api.control(rig,'Bend').setValue(0);
        const flat=cards.map(c=>rendered(rig,c,time));
        api.control(rig,'Bend').setValue(0.000001);
        cards.forEach((c,i)=>{
            const p=rendered(rig,c,time);
            assert.ok(Math.hypot(p.p[0]-flat[i].p[0],p.p[1]-flat[i].p[1])<0.001);
            assert.ok(Math.abs(p.rotation-flat[i].rotation)<0.00001);
        });
    }
    if (orbit) for (const reverse of [false,true]) {
        api.configure(rig,{...settings,bend:50,orbitClockwise:reverse});
        for (let i=0;i<cards.length;i++) {
            const card=cards[reverse?(cards.length-i)%cards.length:i];
            const p=rendered(rig,card,2.9+i*1.4).p;
            near(p[0],0);near(p[1],0);
        }
        for (const c of cards) {
            const first=rendered(rig,c,0),last=rendered(rig,c,api.orbitDuration(settings,cards.length));
            near(first.p[0],last.p[0]);near(first.p[1],last.p[1]);near(first.rotation,last.rotation);
        }
    }
    // A saved v1.6.4 rig acquires the anchor and new tangent on Update, once.
    if (!orbit) {
        const old='// RC bend rotation\nif (parent.effect("Half Circle")(1) > 0.5 && n > 1) {\n'+
            '  var b = Math.max(0, Math.min(200, parent.effect("Bend")(1))) / 100;\n'+
            '  var start = parent.effect("Start Angle")(1);\n'+
            '  if (b === 0) { a = start + 90; }\n'+
            '  else if (b !== 1) {\n'+
            '    var theta = (a-start)*Math.PI/180;\n'+
            '    var normal = Math.atan2(Math.sin(theta), b*Math.cos(theta));\n'+
            '    a += Math.atan2(Math.sin(normal-theta), Math.cos(normal-theta))*180/Math.PI;\n'+
            '  }\n}\n';
        for (const c of cards) {
            const tr=c.property('ADBE Transform Group');
            tr.property('ADBE Anchor Point').expression='';
            tr.property('ADBE Rotate Z').expression=tr.property('ADBE Rotate Z').expression.replace(/\/\/ RC bend rotation v2[\s\S]*?\n\}\n/,old);
        }
        api.configure(rig,{...settings,bend:50});api.configure(rig,{...settings,bend:50});
        for (const c of cards) {
            assert.equal(c.property('ADBE Transform Group').property('ADBE Rotate Z').expression.split('// RC bend rotation').length,2);
            assert.match(c.property('ADBE Transform Group').property('ADBE Anchor Point').expression,/RC bend anchor/);
            const p=rendered(rig,c,5); assert.ok(p.p.every(Number.isFinite));
        }
    }
}
console.log('PASS: circular bow and moving anchors, uniform end-to-end spacing, rigid travel about the bend center, tiny/zero Bend continuity, dimensions/PAR, both modes, centered focus/loops, and v1.6.4 upgrades.');
console.log(`PASS: ${checks} numerical assertions, JSX syntax, input validation, import rollback, undo balancing, and keyframe update behavior.`);
console.log('PASS: project source reuse, mixed sources, failure preservation, selection filtering/deduplication, actual panel callbacks, and destination fallback (stubbed AE/ScriptUI host).');
console.log('PASS: rounded/square mask geometry, corner radius clamping/PAR, GUI load/apply, old-rig upgrades, and existing-mask preservation.');
console.log('PASS: reproducible seed permutations, unique slots, radial/upright orientations, original-order restore, New Seed callback, single image, and legacy-expression upgrades.');
console.log('PASS: reopening/discovery across comps, selected-child and lone-rig detection, settings/source recovery, update without timeline selection, multiple targets, read-only loading, deleted/broken targets, and project switches.');
console.log('PASS: precomp selection/reuse, remembered destination, mixed-source recovery, rounding/shuffle updates, short-comp frame hold, normal long-comp playback, recursive nesting rejection, and failure preservation.');
console.log('PASS: missing-control diagnostics and native error action/step/line preservation through rollback.');
console.log(recoveryResult + ' (Node host; native engine check: Recovery Test.jsx.)');
console.log('Native After Effects GUI/import/render verification requires Smoke Test.jsx.');
